config/routes.rb
Rails.application.routes.draw do
  #devise_for :users, controllers: {
  #  registrations: 'public/registrations',
  #  sessions: 'public/sessions',
  #  passwords: 'public/passwords'
  #}

  devise_for :admins, path: "admin", skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  scope module: :public do
    devise_for :users, controllers: {
      registrations: 'public/registrations'
    }

    root to: 'homes#top'
    get '/myposts' => 'post_blogs#myposts', as: 'myposts'
    get 'about' => 'homes#about', as: 'about'
    
  
    resources :post_blogs, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
      
      collection do
        get 'search'
      end
    end

    resources :users do
      resources :post_blogs, only: [:index, :show]
      member do
        # get :post_blogs
        # get :favorites
        get :followings
        get :followers
      end
    end

    resources :relationships, only: [:create, :destroy]
  end





namespace :admin do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  resources :users, only: [:index, :show, :destroy]
  resources :post_blogs, only: [:index, :show, :destroy]
  resources :post_comments, only: [:index, :destroy]
  get 'dashboard', to: 'dashboards#index'
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  has_many :post_blogs, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :email, presence: true, uniqueness: true

  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpg')
    end
    profile_image #.variant(resize_to_limit: [150, 150])
  end

  def follow(user)
    active_relationships.find_or_create_by(followed_id: user.id) 
  end

  def unfollow(user)
    relationship = active_relationships.find_by(followed_id: user.id)&.destroy
  end

  def following?(user)
    following.include?(user)
  end
    
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_admin!

    def index
        @users = User.order(created_at: :desc)
      end
    
      def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to admin_users_path, notice: "User deleted."
      end
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def new
  end

  def index
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "Profile was successfully updated!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "Failed to update profile."
      render :edit
    end
  end

  def destroy
    @user = current_user
    if @user.destroy
      flash[:notice] = "Account was successfully deleted."
      redirect_to root_path
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container mt-5">
  <div class="card mx-auto" style="max-width: 600px;">
    <div class="card-body">
      <h4 class="card-title text-center mb-4">Edit Profile</h4>

      <%= form_with model: @user, local: true, multipart: true do |f| %>
        <div class="mb-3 text-center">
          <%= image_tag @user.get_profile_image, class: "rounded-circle mb-3", width: 150, height: 150 %>
        </div>

        <div class="form-group">
          <%= f.label :profile_image, "Change Profile Picture" %>
          <%= f.file_field :profile_image, class: "form-control-file" %>
        </div>

        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <%= f.submit "Save Changes", class: "btn btn-primary btn-block" %>
      <% end %>

      <%= link_to "Delete Account", @user, method: :delete, data: { confirm: "Are you sure you want to delete your account?" }, class: "btn btn-danger btn-block mt-2" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="card mx-auto" style="max-width: 600px;">
    <div class="card-body text-center">
      <div class="mb-3 text-center">
        <%= image_tag @user.get_profile_image, class: "rounded-circle mb-3", width: 150, height: 150 %>
      </div>

      <h5 class="text-muted mb-0">Name</h5>
      <h4 class="card-title"><%= @user.name %></h4>
      
      <%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-primary mt-3' %>
      <%= link_to "View My Posts", myposts_path, class: 'btn btn-primary mt-3' %>

    </div>
  </div>
</div>