config/routes.rb
Rails.application.routes.draw do
  #devise_for :users, controllers: {
  #  registrations: 'public/registrations',
  #  sessions: 'public/sessions',
  #  passwords: 'public/passwords'
  #}

  devise_for :admins, path: "admin", skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  scope module: :public do
    devise_for :users, controllers: {
      registrations: 'public/registrations'
    }

    root to: 'homes#top'
    get '/myposts' => 'post_blogs#myposts', as: 'myposts'
    get 'about' => 'homes#about', as: 'about'
    
  
    resources :post_blogs, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
      
      collection do
        get 'search'
      end
    end

    resources :users do
      resources :post_blogs, only: [:index, :show]
      member do
        # get :post_blogs
        # get :favorites
        get :followings
        get :followers
      end
    end

    resources :relationships, only: [:create, :destroy]
  end





namespace :admin do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  resources :users, only: [:index, :show, :destroy]
  resources :post_blogs, only: [:index, :show, :destroy]
  resources :post_comments, only: [:index, :destroy]
  get 'dashboard', to: 'dashboards#index'
end

end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
    layout 'application'
    before_action :authenticate_admin!
    def index
        @users = User.all
    end
end

app/views/admin/dashboards/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <div class="container mt-4">
      <% if admin_signed_in? %>
        <%= link_to "log out", destroy_admin_session_path, method: :delete, class: "btn btn-danger float-right mb-3" %>
      </li>

      <h1>Admin Dashboard</h1>
      <p>Manage users, posts, and comments.</p>

      <ul class="nav nav-tabs">
        <li class="nav-item">
          <%= link_to "Users", admin_users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", admin_post_blogs_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Comments", admin_post_comments_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </body>
  <% end %>
</html>