config/routes.rb
Rails.application.routes.draw do
  #devise_for :users, controllers: {
  #  registrations: 'public/registrations',
  #  sessions: 'public/sessions',
  #  passwords: 'public/passwords'
  #}

  devise_for :admins, path: "admin", skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  scope module: :public do
    devise_for :users, controllers: {
      registrations: 'public/registrations'
    }

    root to: 'homes#top'
    get '/myposts' => 'post_blogs#myposts', as: 'myposts'
    get 'about' => 'homes#about', as: 'about'
    
  
    resources :post_blogs, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
      
      collection do
        get 'search'
      end
    end

    resources :users do
      resources :post_blogs, only: [:index, :show]
      member do
        # get :post_blogs
        # get :favorites
        get :followings
        get :followers
      end
    end

    resources :relationships, only: [:create, :destroy]
  end





namespace :admin do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  resources :users, only: [:index, :show, :destroy]
  resources :post_blogs, only: [:index, :show, :destroy]
  resources :post_comments, only: [:index, :destroy]
  get 'dashboard', to: 'dashboards#index'
end

end

app/views/layouts/_error_messages.html.erb
<% if object && object.errors.any? %>
  <div class="alert alert-danger">
    <h4 class="alert-heading">Oops! Something went wrong:</h4>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= key == "notice" ? "alert-success" : "alert-danger" %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<header class="bg-dark text-white py-3">
  <div class="container">
    <h1 class="m-0">
      <%= link_to 'BLOG ~Believe on Gourmet~', root_path, class: 'text-white text-decoration-none' %>
    </h1>
    <p class="lead">満喫なグルメ冒険</p>
  </div>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
          <li class="nav-item"><%= link_to 'Home', root_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'About', about_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Explore Posts', post_blogs_path, class: 'nav-link' %></li>


          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to 'Upload a Post', new_post_blog_path, class: 'nav-link'%></li>
            <li class="nav-item"><%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'My Posts', myposts_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
          <%= form_with url: search_post_blogs_path, method: :get, local: true, class: 'form-inline my-2 my-lg-0 ml-auto' do |f| %>
            <%= f.search_field :keyword, placeholder: "Search posts...", class: "form-control mr-sm-2" %>
            <%= f.submit "Search", class: "btn btn-outline-light mr-4" %>
          <% end %>
      </div>


      <div class="d-flex">
        <% if user_signed_in? %>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
        <% else %>
          <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary mr-2' %>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' %>
        <% end %>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/73bea634f3.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.8/dist/trix.css">
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>

    <% # <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"> %>
    <% # <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" defer></script> %>  
  </head>

  <body class="bg-light text-dark d-flex flex-column min-vh-100">
    <%= render "layouts/navigation" %>

    <main class="flex-grow-1">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </main>

    <footer class="text-center bg-dark text-light py-3 mt-auto">
      <div class="container">
        <p class="mb-0">&copy; 2025 BLOG — All rights reserved.</p>
      </div>
    </footer>

  </body>
</html>